version: '3'
services:
  mysql:
    image: mysql:8.0.18
    ports:
      - 3306:3306
    volumes:
      - /data/docker/volumes/euler-cloud/mysql/data:/var/lib/mysql
      - ./.init-passwd:/run/secrets/mysql-root
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root

  redis:
    image: redis:5.0.7-alpine
    volumes:
    - /data/docker/volumes/euler-cloud/redis/data:/data
    - /data/docker/volumes/euler-cloud/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  registry:
    image: eulerproject/euler-cloud-registry:1.0.0-SNAPSHOT
    volumes:
    - /data/docker/volumes/euler-cloud/registry/conf:/app/conf:ro
    - /data/docker/volumes/euler-cloud/registry/runtime:/app/runtime
    ports:
    - 28761:8761
    environment:
    - JAVA_OPTS=
      -server
      -Xms256m
      -Xmx256m

  gateway:
    image: eulerproject/euler-cloud-gateway:1.0.0-SNAPSHOT
    volumes:
    - /data/docker/volumes/euler-cloud/gateway/conf:/app/conf:ro
    - /data/docker/volumes/euler-cloud/gateway/runtime:/app/runtime
    ports:
    - 10000:8080
    environment:
    - JAVA_OPTS=
      -server
      -Xms256m
      -Xmx256m

  app-image:
    image: eulerproject/euler-cloud-image:1.0.0-SNAPSHOT
    volumes:
    - /data/docker/volumes/euler-cloud/app-image/conf:/app/conf:ro
    - /data/docker/volumes/euler-cloud/app-image/runtime:/app/runtime
    ports:
    - 10001:8080
    links:
    - mysql
    - redis
    environment:
    - JAVA_OPTS=
      -server
      -Xms256m
      -Xmx256m

  app-uc:
    image: eulerproject/user-center:1.0.0-SNAPSHOT
    volumes:
    - /data/docker/volumes/euler-cloud/app-uc/conf:/usr/local/app/conf:ro
    - /data/docker/volumes/euler-cloud/app-uc/runtime:/user/local/app/runtime
    - /data/docker/volumes/euler-cloud/app-uc/log:/usr/local/tomcat/logs
    ports:
    - 20002:8080
    links:
    - mysql
    - redis
    environment:
    - JAVA_OPTS=
      -server
      -Xms256m
      -Xmx256m
